"""Schemas package."""

from app.schemas.ai import (
    ChatRequest,
    ChatResponse,
    ConversationListItem,
    ConversationListResponse,
    GreetingRequest,
    GreetingResponse,
    PersonaInfo,
    PersonaListResponse,
    QuotaResponse,
)
from app.schemas.auth import (
    AGE_RANGE_OPTIONS,
    CompleteProfileRequest,
    CompleteProfileResponse,
    CurrentUserResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    SendCodeRequest,
    SendCodeResponse,
    VerifyCodeRequest,
    VerifyCodeResponse,
)
from app.schemas.user import (
    UserBase,
    UserDetailResponse,
    UserResponse,
    UserTagResponse,
    UserUpdateRequest,
    UserTagCreateRequest,
    UserTagsResponse,
    UserPublicInfo,
    ProfileTagItem,
    AIProfileTagResponse,
    SocialLevelProgress,
    SocialLevelUnlockStatus,
    SocialLevelResponse,
    BehaviorStats,
    PublicPostItem,
    PublicPostsResponse,
    ImportantDateItem,
    ImportantDatesSchema,
)
from app.schemas.notification import (
    DEFAULT_DISABLED_TYPES,
    DEFAULT_ENABLED_TYPES,
    NotificationListResponse,
    NotificationResponse,
    NotificationSettingResponse,
    NotificationSettingUpdateRequest,
    NotificationType,
    PushFrequencyConfig,
    PushRequest,
    PushResult,
)
from app.schemas.weekly_report import (
    EmptyWeeklyReportResponse,
    WeeklyReportGenerateRequest,
    WeeklyReportHistoryResponse,
    WeeklyReportResponse,
)
from app.schemas.friend import (
    FriendRequestStatus,
    SendFriendRequestRequest,
    AcceptFriendRequestRequest,
    FriendRequestSender,
    FriendRequestResponse,
    FriendRequestListResponse,
    SendFriendRequestResponse,
    FriendUserInfo,
    FriendResponse,
    FriendListResponse,
    BlockUserRequest,
    BlockedUserResponse,
    BlockListResponse,
    BlockUserResponse,
    DeleteFriendResponse,
    HandleFriendRequestResponse,
    OfficialAIInfo,
    CooldownCheckResponse,
)
from app.schemas.social_energy import (
    SocialEnergyResponse,
    RestRequest,
    RestResponse,
)
from app.schemas.ai_chat_assist import (
    TopicSuggestionRequest,
    TopicSuggestionResponse,
    TopicItem,
    ReplySuggestionRequest,
    ReplySuggestionResponse,
    ReplyItem,
    PolishRequest,
    PolishResponse,
    ExitSuggestionRequest,
    ExitSuggestionResponse,
    ExitItem,
)

__all__ = [
    # AI 对话相关
    "ChatRequest",
    "ChatResponse",
    "ConversationListItem",
    "ConversationListResponse",
    "GreetingRequest",
    "GreetingResponse",
    "PersonaInfo",
    "PersonaListResponse",
    "QuotaResponse",
    # 认证相关
    "SendCodeRequest",
    "SendCodeResponse",
    "VerifyCodeRequest",
    "VerifyCodeResponse",
    "CompleteProfileRequest",
    "CompleteProfileResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "CurrentUserResponse",
    "AGE_RANGE_OPTIONS",
    # 用户相关
    "UserBase",
    "UserResponse",
    "UserUpdateRequest",
    "UserTagResponse",
    "UserDetailResponse",
    "UserTagCreateRequest",
    "UserTagsResponse",
    "UserPublicInfo",
    "ProfileTagItem",
    "AIProfileTagResponse",
    "SocialLevelProgress",
    "SocialLevelUnlockStatus",
    "SocialLevelResponse",
    "BehaviorStats",
    "PublicPostItem",
    "PublicPostsResponse",
    "ImportantDateItem",
    "ImportantDatesSchema",
    # 周报相关
    "EmptyWeeklyReportResponse",
    "WeeklyReportGenerateRequest",
    "WeeklyReportHistoryResponse",
    "WeeklyReportResponse",
    # 通知相关
    "NotificationResponse",
    "NotificationListResponse",
    "NotificationSettingResponse",
    "NotificationSettingUpdateRequest",
    "NotificationType",
    "PushRequest",
    "PushResult",
    "PushFrequencyConfig",
    "DEFAULT_ENABLED_TYPES",
    "DEFAULT_DISABLED_TYPES",
    # 好友相关
    "FriendRequestStatus",
    "SendFriendRequestRequest",
    "AcceptFriendRequestRequest",
    "FriendRequestSender",
    "FriendRequestResponse",
    "FriendRequestListResponse",
    "SendFriendRequestResponse",
    "FriendUserInfo",
    "FriendResponse",
    "FriendListResponse",
    "BlockUserRequest",
    "BlockedUserResponse",
    "BlockListResponse",
    "BlockUserResponse",
    "DeleteFriendResponse",
    "HandleFriendRequestResponse",
    "OfficialAIInfo",
    "CooldownCheckResponse",
    # 社交能量相关
    "SocialEnergyResponse",
    "RestRequest",
    "RestResponse",
    # AI 聊天辅助相关
    "TopicSuggestionRequest",
    "TopicSuggestionResponse",
    "TopicItem",
    "ReplySuggestionRequest",
    "ReplySuggestionResponse",
    "ReplyItem",
    "PolishRequest",
    "PolishResponse",
    "ExitSuggestionRequest",
    "ExitSuggestionResponse",
    "ExitItem",
]
