from enum import Enum


class ErrorCode(str, Enum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    MISSING_PARAMETER = "MISSING_PARAMETER"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_MISSING = "TOKEN_MISSING"
    VERIFICATION_CODE_EXPIRED = "VERIFICATION_CODE_EXPIRED"
    VERIFICATION_CODE_INVALID = "VERIFICATION_CODE_INVALID"
    VERIFICATION_CODE_TOO_FREQUENT = "VERIFICATION_CODE_TOO_FREQUENT"
    PASSWORD_INCORRECT = "PASSWORD_INCORRECT"

    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_DISABLED = "USER_DISABLED"
    USER_UNDERAGE = "USER_UNDERAGE"
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE"

    CONTENT_SENSITIVE = "CONTENT_SENSITIVE"
    CONTENT_TOO_LONG = "CONTENT_TOO_LONG"
    CONTENT_EMPTY = "CONTENT_EMPTY"
    CONTENT_AUDIT_FAILED = "CONTENT_AUDIT_FAILED"
    POST_NOT_FOUND = "POST_NOT_FOUND"
    POST_DELETED = "POST_DELETED"
    POST_ACCESS_DENIED = "POST_ACCESS_DENIED"
    PUBLISH_TOO_FREQUENT = "PUBLISH_TOO_FREQUENT"

    FRIEND_REQUEST_NOT_FOUND = "FRIEND_REQUEST_NOT_FOUND"
    FRIEND_REQUEST_EXPIRED = "FRIEND_REQUEST_EXPIRED"
    FRIEND_REQUEST_ALREADY_HANDLED = "FRIEND_REQUEST_ALREADY_HANDLED"
    FRIEND_REQUEST_COOLDOWN = "FRIEND_REQUEST_COOLDOWN"  # 冷却期内不能发送申请
    FRIEND_REQUEST_LIMIT_EXCEEDED = "FRIEND_REQUEST_LIMIT_EXCEEDED"  # 30天内申请次数超限
    ALREADY_FRIENDS = "ALREADY_FRIENDS"
    CANNOT_ADD_SELF = "CANNOT_ADD_SELF"
    FRIEND_LIMIT_EXCEEDED = "FRIEND_LIMIT_EXCEEDED"
    BLOCKED_BY_USER = "BLOCKED_BY_USER"
    USER_ALREADY_BLOCKED = "USER_ALREADY_BLOCKED"  # 已拉黑该用户
    USER_NOT_BLOCKED = "USER_NOT_BLOCKED"  # 未拉黑该用户
    PERMISSION_DENIED = "PERMISSION_DENIED"

    AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE"
    AI_SERVICE_TIMEOUT = "AI_SERVICE_TIMEOUT"
    AI_QUOTA_EXCEEDED = "AI_QUOTA_EXCEEDED"
    AI_CONVERSATION_NOT_FOUND = "AI_CONVERSATION_NOT_FOUND"
    AI_CONTEXT_TOO_LONG = "AI_CONTEXT_TOO_LONG"

    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"

    DIARY_NOT_FOUND = "DIARY_NOT_FOUND"
    DIARY_ACCESS_DENIED = "DIARY_ACCESS_DENIED"
    DIARY_ALREADY_EXISTS = "DIARY_ALREADY_EXISTS"
    DIARY_ENCRYPTION_ERROR = "DIARY_ENCRYPTION_ERROR"
    DIARY_SYNC_CONFLICT = "DIARY_SYNC_CONFLICT"

    # 通知相关 9xxx
    NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
    NOTIFICATION_ALREADY_READ = "NOTIFICATION_ALREADY_READ"
    PUSH_FAILED = "PUSH_FAILED"

    # 举报相关 10xxx
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    REPORT_ALREADY_PROCESSED = "REPORT_ALREADY_PROCESSED"
    APPEAL_NOT_FOUND = "APPEAL_NOT_FOUND"

    # 管理后台 11xxx
    ADMIN_AUTH_FAILED = "ADMIN_AUTH_FAILED"
    ADMIN_PERMISSION_DENIED = "ADMIN_PERMISSION_DENIED"
    ADMIN_ACCOUNT_LOCKED = "ADMIN_ACCOUNT_LOCKED"

    # 对话/私聊相关 12xxx
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_TOO_FREQUENT = "MESSAGE_TOO_FREQUENT"
    WEBSOCKET_CONNECTION_FAILED = "WEBSOCKET_CONNECTION_FAILED"

    # 树洞相关 13xxx
    TREEHOLE_POST_NOT_FOUND = "TREEHOLE_POST_NOT_FOUND"
    RESONATE_ALREADY_EXISTS = "RESONATE_ALREADY_EXISTS"
    COMMENT_TOO_LONG = "COMMENT_TOO_LONG"

    # 动态相关补充 14xxx
    POST_VISIBILITY_DENIED = "POST_VISIBILITY_DENIED"
    FOLLOW_ALREADY_EXISTS = "FOLLOW_ALREADY_EXISTS"

    # 加密相关 15xxx
    ENCRYPTION_KEY_NOT_FOUND = "ENCRYPTION_KEY_NOT_FOUND"
    DECRYPTION_FAILED = "DECRYPTION_FAILED"

    # 周报相关 16xxx
    WEEKLY_REPORT_NOT_FOUND = "WEEKLY_REPORT_NOT_FOUND"
    WEEKLY_REPORT_GENERATION_FAILED = "WEEKLY_REPORT_GENERATION_FAILED"
    WEEKLY_REPORT_NO_DATA = "WEEKLY_REPORT_NO_DATA"

    # 危机干预相关 17xxx
    CRISIS_EVENT_NOT_FOUND = "CRISIS_EVENT_NOT_FOUND"
    CRISIS_EVENT_ALREADY_RESOLVED = "CRISIS_EVENT_ALREADY_RESOLVED"
    CRISIS_ALREADY_RESOLVED = "CRISIS_ALREADY_RESOLVED"

    # 内容管理相关 18xxx
    CONTENT_NOT_FOUND = "CONTENT_NOT_FOUND"
    CONTENT_ALREADY_HIDDEN = "CONTENT_ALREADY_HIDDEN"
    CONTENT_ALREADY_VISIBLE = "CONTENT_ALREADY_VISIBLE"

    # 举报相关补充 19xxx
    REPORT_DUPLICATE = "REPORT_DUPLICATE"

    # 管理后台管理员相关 20xxx
    ADMIN_NOT_FOUND = "ADMIN_NOT_FOUND"
    ADMIN_USERNAME_EXISTS = "ADMIN_USERNAME_EXISTS"
    ADMIN_CANNOT_DELETE_SELF = "ADMIN_CANNOT_DELETE_SELF"
    ADMIN_CANNOT_MODIFY_SUPER_ADMIN = "ADMIN_CANNOT_MODIFY_SUPER_ADMIN"
    ADMIN_PASSWORD_WEAK = "ADMIN_PASSWORD_WEAK"

    # 账户注销相关 21xxx
    ACCOUNT_DELETION_IN_PROGRESS = "ACCOUNT_DELETION_IN_PROGRESS"
    ACCOUNT_DELETION_FAILED = "ACCOUNT_DELETION_FAILED"
    ACCOUNT_ALREADY_DELETED = "ACCOUNT_ALREADY_DELETED"
    DATA_EXPORT_IN_PROGRESS = "DATA_EXPORT_IN_PROGRESS"
    DATA_EXPORT_FAILED = "DATA_EXPORT_FAILED"
    ACCOUNT_HAS_PENDING_FRIEND_REQUESTS = "ACCOUNT_HAS_PENDING_FRIEND_REQUESTS"
